EXPECTED_ALL_PULL_METRICS = {
    "metrics": [
        "pull_request_16",
        "pull_request_15",
        "pull_request_14",
        "pull_request_13",
        "pull_request_12",
        "pull_request_11",
        "pull_request_10",
        "pull_request_9",
        "pull_request_8",
        "pull_request_7",
        "pull_request_6",
        "pull_request_5",
        "pull_request_4",
        "pull_request_3",
        "pull_request_2",
        "pull_request_1",
    ],
    "values": [
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/16",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/16/commits",
            },
            {"metric": "state", "value": "open"},
            {"metric": "number", "value": 16},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-07-03T13:40:18Z"},
            {"metric": "updated_at", "value": "2023-07-08T20:51:22Z"},
            {"metric": "closed_at", "value": None},
            {"metric": "merged_at", "value": None},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/15",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/15/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 15},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-26T18:12:51Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:18Z"},
            {"metric": "closed_at", "value": "2023-06-26T18:12:58Z"},
            {"metric": "merged_at", "value": "2023-06-26T18:12:58Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/14",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/14/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 14},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-26T14:37:04Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:20Z"},
            {"metric": "closed_at", "value": "2023-06-26T17:14:01Z"},
            {"metric": "merged_at", "value": "2023-06-26T17:14:01Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/13",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/13/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 13},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T21:34:13Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:22Z"},
            {"metric": "closed_at", "value": "2023-06-25T21:36:23Z"},
            {"metric": "merged_at", "value": "2023-06-25T21:36:23Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/12",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/12/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 12},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:22:46Z"},
            {"metric": "updated_at", "value": "2023-06-25T16:58:25Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:22:56Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:22:56Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/11",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/11/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 11},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:21:01Z"},
            {"metric": "updated_at", "value": "2023-06-25T06:23:02Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:21:09Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:21:09Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/10",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/10/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 10},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:10:31Z"},
            {"metric": "updated_at", "value": "2023-06-25T06:13:16Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:13:15Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:13:15Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/9",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/9/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 9},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:54:21Z"},
            {"metric": "updated_at", "value": "2023-06-25T04:58:26Z"},
            {"metric": "closed_at", "value": "2023-06-25T04:58:26Z"},
            {"metric": "merged_at", "value": "2023-06-25T04:58:26Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/8",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/8/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 8},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:17:55Z"},
            {"metric": "updated_at", "value": "2023-06-25T04:37:59Z"},
            {"metric": "closed_at", "value": "2023-06-25T04:25:20Z"},
            {"metric": "merged_at", "value": "2023-06-25T04:25:20Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/7",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/7/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 7},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:04:31Z"},
            {"metric": "updated_at", "value": "2023-06-30T04:43:02Z"},
            {"metric": "closed_at", "value": "2023-06-30T04:43:02Z"},
            {"metric": "merged_at", "value": "2023-06-30T04:43:02Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/6",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/6/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 6},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-22T00:44:10Z"},
            {"metric": "updated_at", "value": "2023-06-24T17:58:05Z"},
            {"metric": "closed_at", "value": "2023-06-22T00:47:07Z"},
            {"metric": "merged_at", "value": "2023-06-22T00:47:07Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/5",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/5/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 5},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-22T00:03:58Z"},
            {"metric": "updated_at", "value": "2023-06-24T17:57:59Z"},
            {"metric": "closed_at", "value": "2023-06-22T00:47:20Z"},
            {"metric": "merged_at", "value": "2023-06-22T00:47:20Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/4",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/4/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 4},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-21T23:30:04Z"},
            {"metric": "updated_at", "value": "2023-06-21T23:38:46Z"},
            {"metric": "closed_at", "value": "2023-06-21T23:34:23Z"},
            {"metric": "merged_at", "value": "2023-06-21T23:34:23Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/3",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/3/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 3},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-19T05:05:20Z"},
            {"metric": "updated_at", "value": "2023-06-21T23:38:49Z"},
            {"metric": "closed_at", "value": "2023-06-19T21:55:01Z"},
            {"metric": "merged_at", "value": "2023-06-19T21:55:01Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/2",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/2/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 2},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-10T01:27:00Z"},
            {"metric": "updated_at", "value": "2023-06-16T00:53:33Z"},
            {"metric": "closed_at", "value": "2023-06-10T01:28:26Z"},
            {"metric": "merged_at", "value": "2023-06-10T01:28:26Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/1",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/1/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 1},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-08T20:18:15Z"},
            {"metric": "updated_at", "value": "2023-06-16T00:53:39Z"},
            {"metric": "closed_at", "value": "2023-06-12T13:41:46Z"},
            {"metric": "merged_at", "value": "2023-06-12T13:41:46Z"},
        ],
    ],
}

EXPECTED_PULL_METRICS = {
    "metrics": [
        "issue_url",
        "commits_url",
        "state",
        "open_issues",
        "closed_issues",
        "created_at",
        "updated_at",
        "closed_at",
        "merged_at",
    ],
    "values": [
        "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/16",
        "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/16/commits",
        "open",
        None,
        None,
        "2023-07-03T13:40:18Z",
        "2023-07-08T20:51:22Z",
        None,
        None,
    ],
}

EXPECTED_COMMUNITY_RETURN_METRICS = {
    "metrics": [
        "health_percentage",
        "updated_at",
        "created_at",
        "watchers_count",
        "forks_count",
        "open_issues_count",
        "forks",
        "open_issues",
        "watchers",
        "subscribers_count",
        "size",
    ],
    "values": [50, None, "2023-05-25T02:21:31Z", 0, 0, 1, 0, 1, 0, 5, 94],
}


EXPECTED_COMMIT_FREQUENCY_METRICS = {
    "metrics": [
        "commits_on_sunday",
        "commits_on_monday",
        "commits_on_tuesday",
        "commits_on_wednesday",
        "commits_on_thursday",
        "commits_on_friday",
        "commits_on_saturday",
    ],
    "values": [23, 3, 0, 7, 17, 15, 3],
}


EXPECT_EXTRACT_METRICS = {
    "metrics": [
        "health_percentage",
        "updated_at",
        "created_at",
        "watchers_count",
        "forks_count",
        "open_issues_count",
        "forks",
        "open_issues",
        "watchers",
        "subscribers_count",
        "size",
        "commits_on_sunday",
        "commits_on_monday",
        "commits_on_tuesday",
        "commits_on_wednesday",
        "commits_on_thursday",
        "commits_on_friday",
        "commits_on_saturday",
        "total_issues",
        "resolved_issues",
        "resolved_ratio",
        "pull_request_16",
        "pull_request_15",
        "pull_request_14",
        "pull_request_13",
        "pull_request_12",
        "pull_request_11",
        "pull_request_10",
        "pull_request_9",
        "pull_request_8",
        "pull_request_7",
        "pull_request_6",
        "pull_request_5",
        "pull_request_4",
        "pull_request_3",
        "pull_request_2",
        "pull_request_1",
    ],
    "values": [
        50,
        None,
        "2023-05-25T02:21:31Z",
        0,
        0,
        1,
        0,
        1,
        0,
        5,
        94,
        23,
        3,
        0,
        7,
        17,
        15,
        3,
        16,
        15,
        0.9375,
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/16",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/16/commits",
            },
            {"metric": "state", "value": "open"},
            {"metric": "number", "value": 16},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-07-03T13:40:18Z"},
            {"metric": "updated_at", "value": "2023-07-08T20:51:22Z"},
            {"metric": "closed_at", "value": None},
            {"metric": "merged_at", "value": None},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/15",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/15/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 15},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-26T18:12:51Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:18Z"},
            {"metric": "closed_at", "value": "2023-06-26T18:12:58Z"},
            {"metric": "merged_at", "value": "2023-06-26T18:12:58Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/14",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/14/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 14},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-26T14:37:04Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:20Z"},
            {"metric": "closed_at", "value": "2023-06-26T17:14:01Z"},
            {"metric": "merged_at", "value": "2023-06-26T17:14:01Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/13",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/13/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 13},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T21:34:13Z"},
            {"metric": "updated_at", "value": "2023-06-29T04:05:22Z"},
            {"metric": "closed_at", "value": "2023-06-25T21:36:23Z"},
            {"metric": "merged_at", "value": "2023-06-25T21:36:23Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/12",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/12/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 12},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:22:46Z"},
            {"metric": "updated_at", "value": "2023-06-25T16:58:25Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:22:56Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:22:56Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/11",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/11/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 11},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:21:01Z"},
            {"metric": "updated_at", "value": "2023-06-25T06:23:02Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:21:09Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:21:09Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/10",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/10/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 10},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T06:10:31Z"},
            {"metric": "updated_at", "value": "2023-06-25T06:13:16Z"},
            {"metric": "closed_at", "value": "2023-06-25T06:13:15Z"},
            {"metric": "merged_at", "value": "2023-06-25T06:13:15Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/9",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/9/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 9},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:54:21Z"},
            {"metric": "updated_at", "value": "2023-06-25T04:58:26Z"},
            {"metric": "closed_at", "value": "2023-06-25T04:58:26Z"},
            {"metric": "merged_at", "value": "2023-06-25T04:58:26Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/8",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/8/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 8},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:17:55Z"},
            {"metric": "updated_at", "value": "2023-06-25T04:37:59Z"},
            {"metric": "closed_at", "value": "2023-06-25T04:25:20Z"},
            {"metric": "merged_at", "value": "2023-06-25T04:25:20Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/7",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/7/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 7},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-25T04:04:31Z"},
            {"metric": "updated_at", "value": "2023-06-30T04:43:02Z"},
            {"metric": "closed_at", "value": "2023-06-30T04:43:02Z"},
            {"metric": "merged_at", "value": "2023-06-30T04:43:02Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/6",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/6/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 6},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-22T00:44:10Z"},
            {"metric": "updated_at", "value": "2023-06-24T17:58:05Z"},
            {"metric": "closed_at", "value": "2023-06-22T00:47:07Z"},
            {"metric": "merged_at", "value": "2023-06-22T00:47:07Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/5",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/5/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 5},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-22T00:03:58Z"},
            {"metric": "updated_at", "value": "2023-06-24T17:57:59Z"},
            {"metric": "closed_at", "value": "2023-06-22T00:47:20Z"},
            {"metric": "merged_at", "value": "2023-06-22T00:47:20Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/4",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/4/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 4},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-21T23:30:04Z"},
            {"metric": "updated_at", "value": "2023-06-21T23:38:46Z"},
            {"metric": "closed_at", "value": "2023-06-21T23:34:23Z"},
            {"metric": "merged_at", "value": "2023-06-21T23:34:23Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/3",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/3/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 3},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-19T05:05:20Z"},
            {"metric": "updated_at", "value": "2023-06-21T23:38:49Z"},
            {"metric": "closed_at", "value": "2023-06-19T21:55:01Z"},
            {"metric": "merged_at", "value": "2023-06-19T21:55:01Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/2",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/2/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 2},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-10T01:27:00Z"},
            {"metric": "updated_at", "value": "2023-06-16T00:53:33Z"},
            {"metric": "closed_at", "value": "2023-06-10T01:28:26Z"},
            {"metric": "merged_at", "value": "2023-06-10T01:28:26Z"},
        ],
        [
            {
                "metric": "issue_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/issues/1",
            },
            {
                "metric": "commits_url",
                "value": "https://api.github.com/repos/fga-eps-mds/2023-1-MeasureSoftGram-Parser/pulls/1/commits",
            },
            {"metric": "state", "value": "closed"},
            {"metric": "number", "value": 1},
            {"metric": "draft", "value": False},
            {"metric": "created_at", "value": "2023-06-08T20:18:15Z"},
            {"metric": "updated_at", "value": "2023-06-16T00:53:39Z"},
            {"metric": "closed_at", "value": "2023-06-12T13:41:46Z"},
            {"metric": "merged_at", "value": "2023-06-12T13:41:46Z"},
        ],
    ],
    "file_paths": "fga-eps-mds/2023-1-MeasureSoftGram-Parser",
}
